name: pyrate
channels:
- conda-forge
- ioos
dependencies:
- cython
- flask
- pyhdf
- gdal
#- grib_api
- hdf4
- hdf5
- ipython
- matplotlib=1.5.1
- networkx
- numpy
# - pygrib
- pyproj
- scipy
- nose
- pillow
- joblib
- pytest
- pytest-cov
- glob2
- mpi4py
- netcdf4
- pip:
  - luigi==1.3.0
  - pyYAML
